### ISSUE TITLE
Default parameters and loadable parameters

### ISSUE THREAD

**Issue by wadoon** [CognitionGuidedSurgery/msml#18]
It could  be useful to define a set of default parameters for the operators for one msml file.

e.g:

``` xml
<msml default-parameters-file="params.yaml" > 

</msml>
```

``` yaml
# params.yaml
stl2vtk:
  optimize:  True
tetgen:
  crit: 0.3
```

The same thing could be useful for msml variables. You can see your msml file as a routine with a set of input variables (file names, ...) and define different execution sets.

``` xml
<msml ...>
  <variables load-file="example-set-1.yaml">
     <!-- define variables here -->
  </variables>
</msml>
```
